services:
  webserver:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #depends_on:
    #  - php
