services:
  php:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: symfony-php
    volumes:
      - ./app/quick_tour:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    #depends_on:
    #  - db
    working_dir: /var/www/html

  webserver:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      #  - "8080:80"
      - 80:80
    volumes:
      - ./app/quick_tour:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
